"""
プロジェクト全体で使用する定数を管理するモジュール
"""

# プラグイン名・プロバイダ名
PLUGIN_NAME = "Kumoy"

# ログメッセージのカテゴリ名（QgsMessageLogで使用）
LOG_CATEGORY = PLUGIN_NAME

# ブラウザパネルのルートパス
BROWSER_ROOT_PATH = "kumoy:/"

# データプロバイダー関連
DATA_PROVIDER_KEY = "kumoy"
DATA_PROVIDER_DESCRIPTION = "Kumoy Data Provider"

# 各種名称の最大文字数
MAX_CHARACTERS_ORGANIZATION_NAME = 32
MAX_CHARACTERS_PROJECT_NAME = 32
MAX_CHARACTERS_PROJECT_DESCRIPTION = 255
MAX_CHARACTERS_VECTOR_NAME = 32
MAX_CHARACTERS_VECTOR_ATTRIBUTION = 255
MAX_CHARACTERS_STYLEDMAP_NAME = 32
MAX_CHARACTERS_STYLEDMAP_ATTRIBUTION = 255
MAX_CHARACTERS_STYLEDMAP_DESCRIPTION = 255

# Kumoyのシステム上の制限
MAX_CHARACTERS_STRING_FIELD = 255
MAX_WKB_LENGTH = 10_000_000  # WKBのbase64エンコード後の最大文字列長

# 予約しているカラム名の接頭辞
RESERVED_FIELD_NAME_PREFIX = "kumoy_"
